version: '3'
services:
  frontend:
    image: src/web-app
    build: 
      context: ./web-app
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"  
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "10000:10000"